### PR TITLE
Propose topic for Karel Ha

### PR DESCRIPTION
**Pull request by mathemage**
@foxik I've given 4 alternatives because I (kind of) do not know which to choose. I have talked about AlphaZero already (at http://ktiml.mff.cuni.cz/~bartak/ui_seminar/talks/2017ZS/KarelHa_AlphaZero.pdf ) so that could be considered cheating (or at least as "using cheat codes"). Can you suggest or give advice what would be the best for the seminar? Thanks!

### CODE REVIEW

**Comment by foxik** [comment]
Generally any of the 4 papers work -- I have read all of them and all are suitable for the DLS, you can even talk about the AlphaZero (hopefully the journal version could be released at the time of the talk :-). Also, I think that you can concentrate on more details than what is currently in the slides.

Do you want to decide now or should I merge with all four papers?

**Comment by mathemage** [comment]
@foxik You can keep all 4 alternative and merge. I will decide on the final one, if I may please. What's the latest date you need to know for sure?

Perhaps I can talk about all of AlphaGo Zero + AlphaZero + the Hex - could be a nice overview of superhuman game-playing AIs ;-)

**Comment by foxik** [comment]
You have to decide only a week before the talk itself, so there is actually plenty of time.

**Comment by mathemage** [comment]
@foxik OK, thank you! ^_^

**Pull request merged**
