### PR TITLE
vainer: add presentation topic

### PR DESCRIPTION
**Pull request by LordOfLuck**
I will talk about normalizing flows, why they are interesting and what are the advantages. I want to mention Autoregressive flows, touch on parallel wavenet and how IAF and MAF complement each other for training and inference. I will take a deeper look at Real NVP.

### CODE REVIEW

**Comment by foxik** [comment]
Maybe it would make sense to also mention Glow https://arxiv.org/abs/1807.03039 after Real NVP?

**Comment by LordOfLuck** [comment]
Sure, why not😊

**Comment by foxik** [comment]
If you agree, could you add Glow to the program then, please?

**Comment by foxik** [comment]
Thanks!

**Pull request merged**
