### PR TITLE
proposition of topic for the 15 May 2018 seminar

### PR DESCRIPTION
**Pull request by VojtechCermak**

### CODE REVIEW

**Comment by foxik** [comment]
The adversarial patch paper seems to be quite short for the whole seminar. How about also including the  https://arxiv.org/pdf/1707.08945.pdf paper, which also discusses real-world adversarial images (it is even referenced from the adversarial patch paper)?

**Comment by foxik** [comment]
Bump

**Comment by VojtechCermak** [comment]
The paper is indeed interesting.
I was thinking about some papers regarding defences to the attack, such as https://openreview.net/pdf?id=BkJ3ibb0- , but it is probably too off topic to the adversary patch paper.

**Comment by foxik** [comment]
On the contrary -- if you like the defense paper, it would be a great choice. So are we talking about the adversarial patch and the defense paper?

**Comment by foxik** [comment]
Yes, please, I will then merge it.

**Pull request closed without merging**
